nombre = input("Ingrese su nombre: ")
tel = input("Ingrese su número de celular: ")
edad = input("Ingrese su edad: ")
altura = input("Ingrese su altura: ")
informacion = tuple((nombre, edad, altura))
direccion = input("Ingrese su dirección: ")
direccion_2 = input("Si tiene alguna otra dirección (padres, pareja, etc) ingresela: ")
direcciones = tuple((direccion, direccion_2))
educacion_1 = input("¿Qué nivel de educación tiene (primaria, bachillerato, etc): ")
educacion_2 = input("¿Tiene algún curso o título?: ")
educacion = tuple((educacion_1, educacion_2))
exp_labo_1 = input("¿Cuántos años de experiencia laboral tiene?( _ años): ")
exp_labo_2 = input("¿Qué experiencia laboral tiene (empresas en las que ha trabajado, algo en lo que se destaque, etc): ")
exp_labo = tuple((exp_labo_1, exp_labo_2))
print("Información: ")
print(informacion [0:3])
print("----")
print("Direccion: ")
print(direcciones [:1])
print("Direccion 2: ")
print(direcciones [1:])
print("----")
print("Educacion: ")
print(educacion[ :1])
print("Curso o título extra: ")
print(educacion [1:])
print("----")
print("Experiencia laboral (años): ")
print(exp_labo [:1])
print("Otra experiencia laboral: ")
print(exp_labo [1:])